# Generated by Django 4.1.6 on 2023-03-22 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eclData", "0002_alter_citygeojson_geojson_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="group",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="city",
            name="propername",
            field=models.CharField(default="1", max_length=200),
            preserve_default=False,
        ),
    ]
