# Generated by Django 4.1.6 on 2023-03-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eclData", "0003_city_group_city_propername"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="costofLivingIndex",
            field=models.CharField(default="N/A", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="city",
            name="rentIndex",
            field=models.CharField(default="0", max_length=50),
            preserve_default=False,
        ),
    ]
