# Generated by Django 4.1.6 on 2023-03-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eclData", "0005_city_costoflivingplusrentindex"),
    ]

    operations = [
        migrations.RemoveField(model_name="city", name="CostOfLivingPlusRentIndex",),
        migrations.RemoveField(model_name="city", name="costofLivingIndex",),
        migrations.RemoveField(model_name="city", name="rentIndex",),
        migrations.AddField(
            model_name="data",
            name="rank",
            field=models.CharField(default="0", max_length=50),
            preserve_default=False,
        ),
    ]
