# Generated by Django 4.1.6 on 2023-03-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eclData", "0006_remove_city_costoflivingplusrentindex_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="rank",
            field=models.CharField(default="0", max_length=50),
            preserve_default=False,
        ),
    ]
