# Generated by Django 4.1.6 on 2023-03-26 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eclData", "0007_city_rank"),
    ]

    operations = [
        migrations.RenameField(model_name="city", old_name="rank", new_name="ranking",),
    ]
